### ISSUE TITLE
Issues while configuring hush

### ISSUE THREAD

**Issue by danielcbit** [natankeddem/hush#1]
The server being used is HP DL380e Gen8

I used a bash script that issued the commands to iLo4 using ssh to quiet it down and used the same user and password in the settings for Hush.

It took me some time to figure out how to properly configure it and use correctly.

Using the test functionality seems to work correctly at first. All tests were "successful" but fans didn't spinned down.

Upon checking the logs I noticed the following:

```
2024-03-22T07:15:25.701081938Z 2024-03-22 07:15:25,700-ERROR-hush.control-1::control|46:: 'HP DL380e'
2024-03-22T07:15:25.701095179Z Traceback (most recent call last):
2024-03-22T07:15:25.701100773Z   File "/app/hush/control.py", line 40, in run
2024-03-22T07:15:25.701105634Z     await self._calc()
2024-03-22T07:15:25.701110035Z   File "/app/hush/control.py", line 55, in _calc
2024-03-22T07:15:25.701114513Z     driver = await Factory.driver(self._host, sensor)
2024-03-22T07:15:25.701119196Z              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-22T07:15:25.701123731Z   File "/app/hush/hardware/factory.py", line 34, in driver
2024-03-22T07:15:25.701128425Z     cls.drivers[host][group]["name"] = name
2024-03-22T07:15:25.701132954Z     ~~~~~~~~~~~^^^^^^
2024-03-22T07:15:25.701137350Z KeyError: 'HP DL380e'
```
When I tested removing the space from the name, then things started to work. Maybe add this in a brief configuration FAQ.

However, I'm still having issues while trying to configuring SSH access to the host.

I'm getting the following errors in the Docker Logs:

```
2024-03-22T07:37:42.255128179Z 2024-03-22 07:37:42,254-ERROR-hush.tabs.configure-1::configure|123:: cannot convert float NaN to integer
2024-03-22T07:37:42.255151353Z Traceback (most recent call last):
2024-03-22T07:37:42.255157515Z   File "/app/hush/tabs/configure.py", line 115, in _test
2024-03-22T07:37:42.255162511Z     temperature = await device.get_temp()
2024-03-22T07:37:42.255167038Z                   ^^^^^^^^^^^^^^^^^^^^^^^
2024-03-22T07:37:42.255171412Z   File "/app/hush/hardware/smart.py", line 52, in get_temp
2024-03-22T07:37:42.255189178Z     raise e
2024-03-22T07:37:42.255193407Z   File "/app/hush/hardware/smart.py", line 47, in get_temp
2024-03-22T07:37:42.255197796Z     self._temp = int(np.mean(drive_temps))
2024-03-22T07:37:42.255202182Z                  ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-22T07:37:42.255206582Z ValueError: cannot convert float NaN to integer
```

Providing the server IP, user and password and clicking in "SEND KEY" yields the following error:

<img width="1348" alt="Screenshot 2024-03-22 at 00 34 06" src="https://github.com/natankeddem/hush/assets/1588135/a3879519-7be3-42aa-8c4a-ea7d626037cb">

Test fails.

I tried to get the info directly from the host ( which is running Proxmox) and commands work fine there.

Any idea of what I am missing ?

**Comment by danielcbit** [comment]
I checked the code and tried to run the ssh command from the docker image that install the ssh key:

```
https://github.com/natankeddem/hush/blob/24e0423da61dac1e0568c25d09a4f4ec8f511f12/hush/interfaces/ssh.py#L115C17-L115C27
```

Deployment of the key is successful: 

```
/usr/bin/ssh-copy-id: INFO: Source of key(s) to be installed: "id_rsa.pub"

Number of key(s) added: 1

Now try logging into the machine, with:   "ssh -o 'IdentitiesOnly=yes' -o 'StrictHostKeychecking=no' 'root@10.0.0.110'"
and check to make sure that only the key(s) you wanted were added.
```

However, when I try to login, I'm still being asked for a password:

```
root@d3f3a83d23fc:/app/data# ssh -o 'IdentitiesOnly=yes' -o 'StrictHostKeychecking=no' 'root@10.0.0.110'
root@10.0.0.110's password: 
```

**Comment by natankeddem** [comment]
Thank you for bringing up your problems. I want to verify a few things on my end before I can give full feedback, this might take me a couple of days. 

I think you are going on a good train of thought on troubleshooting by logging into the container. To utilize `ssh` as the app uses it you will need to include the path to the config:
```
ssh -F {config_path} {host}
```
The path should be `/app/data/config` I believe. You might also want to use `-vvv` to give a more verbose output from `ssh`. In addition, not utilizing a key should also be possible if you don't hit the "SEND" button and just save with the password in the field.

**Comment by danielcbit** [comment]
Hi @natankeddem 

Thanks for checking about it and for this great tool!

I tried to test the SSH connection again as you mentioned and the outcome was the same: 

Contents of /app/data/config
```
root@d3f3a83d23fc:/app/data# cat /app/data/config
Host HPDL380e
    IdentityFile /app/data/id_rsa
    StrictHostKeychecking no
    IdentitiesOnly yes
    PasswordAuthentication no

Host HPDL380e_oob
    IdentityFile /app/data/id_rsa
    StrictHostKeychecking no
    IdentitiesOnly yes
    PasswordAuthentication yes
    ...
```

SSH Logs: 

```
root@d3f3a83d23fc:/app# ssh -vvv -F /app/data/config root@10.0.0.110
OpenSSH_9.2p1 Debian-2+deb12u2, OpenSSL 3.0.11 19 Sep 2023
debug1: Reading configuration data /app/data/config
debug3: kex names ok: [diffie-hellman-group14-sha1]
debug2: resolve_canonicalize: hostname 10.0.0.110 is address
debug3: expanded UserKnownHostsFile '~/.ssh/known_hosts' -> '/root/.ssh/known_hosts'
debug3: expanded UserKnownHostsFile '~/.ssh/known_hosts2' -> '/root/.ssh/known_hosts2'
debug3: ssh_connect_direct: entering
debug1: Connecting to 10.0.0.110 [10.0.0.110] port 22.
debug3: set_sock_tos: set socket 3 IP_TOS 0x10
debug1: Connection established.
debug1: identity file /root/.ssh/id_rsa type -1
debug1: identity file /root/.ssh/id_rsa-cert type -1
debug1: identity file /root/.ssh/id_ecdsa type -1
debug1: identity file /root/.ssh/id_ecdsa-cert type -1
debug1: identity file /root/.ssh/id_ecdsa_sk type -1
debug1: identity file /root/.ssh/id_ecdsa_sk-cert type -1
debug1: identity file /root/.ssh/id_ed25519 type -1
debug1: identity file /root/.ssh/id_ed25519-cert type -1
debug1: identity file /root/.ssh/id_ed25519_sk type -1
debug1: identity file /root/.ssh/id_ed25519_sk-cert type -1
debug1: identity file /root/.ssh/id_xmss type -1
debug1: identity file /root/.ssh/id_xmss-cert type -1
debug1: identity file /root/.ssh/id_dsa type -1
debug1: identity file /root/.ssh/id_dsa-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_9.2p1 Debian-2+deb12u2
debug1: Remote protocol version 2.0, remote software version OpenSSH_8.4p1 Debian-5+deb11u3
debug1: compat_banner: match: OpenSSH_8.4p1 Debian-5+deb11u3 pat OpenSSH* compat 0x04000000
debug2: fd 3 setting O_NONBLOCK
debug1: Authenticating to 10.0.0.110:22 as 'root'
debug3: record_hostkey: found key type ED25519 in file /root/.ssh/known_hosts:2
debug3: record_hostkey: found key type ECDSA in file /root/.ssh/known_hosts:3
debug3: load_hostkeys_file: loaded 2 keys from 10.0.0.110
debug1: load_hostkeys: fopen /root/.ssh/known_hosts2: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
debug3: order_hostkeyalgs: have matching best-preference key type ssh-ed25519-cert-v01@openssh.com, using HostkeyAlgorithms verbatim
debug3: send packet: type 20
debug1: SSH2_MSG_KEXINIT sent
debug3: receive packet: type 20
debug1: SSH2_MSG_KEXINIT received
debug2: local client KEXINIT proposal
debug2: KEX algorithms: sntrup761x25519-sha512@openssh.com,curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,ext-info-c,kex-strict-c-v00@openssh.com
debug2: host key algorithms: ssh-ed25519-cert-v01@openssh.com,ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,sk-ssh-ed25519-cert-v01@openssh.com,sk-ecdsa-sha2-nistp256-cert-v01@openssh.com,rsa-sha2-512-cert-v01@openssh.com,rsa-sha2-256-cert-v01@openssh.com,ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,sk-ssh-ed25519@openssh.com,sk-ecdsa-sha2-nistp256@openssh.com,rsa-sha2-512,rsa-sha2-256
debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: compression ctos: none,zlib@openssh.com,zlib
debug2: compression stoc: none,zlib@openssh.com,zlib
debug2: languages ctos: 
debug2: languages stoc: 
debug2: first_kex_follows 0 
debug2: reserved 0 
debug2: peer server KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,kex-strict-s-v00@openssh.com
debug2: host key algorithms: rsa-sha2-512,rsa-sha2-256,ssh-rsa,ecdsa-sha2-nistp256,ssh-ed25519
debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: compression ctos: none,zlib@openssh.com
debug2: compression stoc: none,zlib@openssh.com
debug2: languages ctos: 
debug2: languages stoc: 
debug2: first_kex_follows 0 
debug2: reserved 0 
debug3: kex_choose_conf: will use strict KEX ordering
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: ssh-ed25519
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug3: send packet: type 30
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug3: receive packet: type 31
debug1: SSH2_MSG_KEX_ECDH_REPLY received
debug1: Server host key: ssh-ed25519 SHA256:8EZcXdDvSgJyzZlbMJC744T4Z6uYUW+gq3vrZX7S+4Y
debug3: record_hostkey: found key type ED25519 in file /root/.ssh/known_hosts:2
debug3: record_hostkey: found key type ECDSA in file /root/.ssh/known_hosts:3
debug3: load_hostkeys_file: loaded 2 keys from 10.0.0.110
debug1: load_hostkeys: fopen /root/.ssh/known_hosts2: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
debug1: Host '10.0.0.110' is known and matches the ED25519 host key.
debug1: Found key in /root/.ssh/known_hosts:2
debug3: send packet: type 21
debug1: ssh_packet_send2_wrapped: resetting send seqnr 3
debug2: ssh_set_newkeys: mode 1
debug1: rekey out after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug3: receive packet: type 21
debug1: ssh_packet_read_poll2: resetting read seqnr 3
debug1: SSH2_MSG_NEWKEYS received
debug2: ssh_set_newkeys: mode 0
debug1: rekey in after 134217728 blocks
debug1: Will attempt key: /root/.ssh/id_rsa 
debug1: Will attempt key: /root/.ssh/id_ecdsa 
debug1: Will attempt key: /root/.ssh/id_ecdsa_sk 
debug1: Will attempt key: /root/.ssh/id_ed25519 
debug1: Will attempt key: /root/.ssh/id_ed25519_sk 
debug1: Will attempt key: /root/.ssh/id_xmss 
debug1: Will attempt key: /root/.ssh/id_dsa 
debug2: pubkey_prepare: done
debug3: send packet: type 5
debug3: receive packet: type 7
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,sk-ssh-ed25519@openssh.com,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,sk-ecdsa-sha2-nistp256@openssh.com,webauthn-sk-ecdsa-sha2-nistp256@openssh.com>
debug3: receive packet: type 6
debug2: service_accept: ssh-userauth
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug3: send packet: type 50
debug3: receive packet: type 51
debug1: Authentications that can continue: publickey,password
debug3: start over, passed a different list publickey,password
debug3: preferred publickey,keyboard-interactive,password
debug3: authmethod_lookup publickey
debug3: remaining preferred: keyboard-interactive,password
debug3: authmethod_is_enabled publickey
debug1: Next authentication method: publickey
debug1: Trying private key: /root/.ssh/id_rsa
debug3: no such identity: /root/.ssh/id_rsa: No such file or directory
debug1: Trying private key: /root/.ssh/id_ecdsa
debug3: no such identity: /root/.ssh/id_ecdsa: No such file or directory
debug1: Trying private key: /root/.ssh/id_ecdsa_sk
debug3: no such identity: /root/.ssh/id_ecdsa_sk: No such file or directory
debug1: Trying private key: /root/.ssh/id_ed25519
debug3: no such identity: /root/.ssh/id_ed25519: No such file or directory
debug1: Trying private key: /root/.ssh/id_ed25519_sk
debug3: no such identity: /root/.ssh/id_ed25519_sk: No such file or directory
debug1: Trying private key: /root/.ssh/id_xmss
debug3: no such identity: /root/.ssh/id_xmss: No such file or directory
debug1: Trying private key: /root/.ssh/id_dsa
debug3: no such identity: /root/.ssh/id_dsa: No such file or directory
debug2: we did not send a packet, disable method
debug3: authmethod_lookup password
debug3: remaining preferred: ,password
debug3: authmethod_is_enabled password
debug1: Next authentication method: password
root@10.0.0.110's password: 
```

**Comment by natankeddem** [comment]
Can you try:
```
ssh -vvv -F /app/data/config HPDL380e
```

**Comment by danielcbit** [comment]
Here is the result:

```
root@d3f3a83d23fc:/app# ssh -vvv -F /app/data/config HPDL380e
OpenSSH_9.2p1 Debian-2+deb12u2, OpenSSL 3.0.11 19 Sep 2023
debug1: Reading configuration data /app/data/config
debug1: /app/data/config line 1: Applying options for HPDL380e
debug3: kex names ok: [diffie-hellman-group14-sha1]
debug3: expanded UserKnownHostsFile '~/.ssh/known_hosts' -> '/root/.ssh/known_hosts'
debug3: expanded UserKnownHostsFile '~/.ssh/known_hosts2' -> '/root/.ssh/known_hosts2'
debug2: resolving "hpdl380e" port 22
debug3: resolve_host: lookup hpdl380e:22
ssh: Could not resolve hostname hpdl380e: Temporary failure in name resolution
```

Which is expected as there is no DNS enrtry in my network for `hpdl380e`.

However, if I edit the config file and add Host parameter to it:

```
root@d3f3a83d23fc:/app# cat /app/data/config
Host HPDL380e
    IdentityFile /app/data/id_rsa
    StrictHostKeychecking no
    IdentitiesOnly yes
    PasswordAuthentication no
    HostName 10.0.0.110
```

Connection is successfull:

```
root@d3f3a83d23fc:/app# ssh -F /app/data/config HPDL380e
Linux cara 5.15.143-1-pve #1 SMP PVE 5.15.143-1 (2024-02-08T18:12Z) x86_64

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Fri Mar 22 13:32:26 2024 from 10.0.0.105
root@cara:~# 
```

**Comment by danielcbit** [comment]
For the non oob entry in /app/data/config, it seems that the host information is not being stored which leads to connection failure

**Comment by danielcbit** [comment]
One last thing. I noticed that if I leave SMART configured for my server entry, the server does not spindown. I clicked on test and the fans only spinned up. Removing SMART config allows the server to spin fans UP and Down as I think it is the expected behavior for testing.

**Comment by natankeddem** [comment]
So a few things to unpack here. Let me start off by showing my test. I utilized a HP G8 Microserver running Proxmox (8.1.4). Here is how I added my host for reference.
[google_screen_recording_2024-03-22T22-49_31.501Z.webm](https://github.com/natankeddem/hush/assets/44515217/6cf56a03-dfe4-48d2-9a0e-b6f18d664883)

Could you try to start over? Delete the data folder contents and try adding the oob/ssh as shown in that video. Don't try to utilize DNS to start just enter IP addresses.

I am not seeing any issue with how the config is being utilized, but maybe I am missing something? Mine populated the hostnames fine:
```
Host a
    IdentityFile /app/data/id_rsa
    StrictHostKeychecking no
    IdentitiesOnly yes
    PasswordAuthentication no
    HostName 10.1.3.7
    User root

Host a_oob
    IdentityFile /app/data/id_rsa
    StrictHostKeychecking no
    IdentitiesOnly yes
    PasswordAuthentication yes
    HostName 10.1.2.7
    User Administrator
    PubKeyAcceptedKeyTypes +ssh-rsa
    HostKeyAlgorithms +ssh-dss
    KexAlgorithms +diffie-hellman-group14-sha1
```

The way it works is that when you hit the "TEST" button for the "Speed Controller" it will set the fans to full speed. They will only ramp down to the fan curve speed once **ALL** of the sensors selected have no errors in processing. If any of the sensors give an error the speed controller will not get set.

There does appear to be some issues associated with utilizing spaces in the naming the server. I will need to do some further investigation into allowing the use somehow or sanitizing/warning during input better.

**Comment by natankeddem** [comment]
Did you resolve your problems @danielcbit?

**Comment by danielcbit** [comment]
Hi.

I re-did the steps as according to the video, still no success.

The messages I got were the same as in your video, but the SMART still fails.

My server has two disks (sda and nvme0), would it be possible that the commands failing to get the data because of that?

Log errors from Container:

```
2024-03-28T06:33:19.296554640Z 2024-03-28 06:33:19,296-ERROR-hush.control-1::control|44:: Connection to DL380e failed!
2024-03-28T06:33:19.296972085Z 2024-03-28 06:33:19,296-ERROR-hush.control-1::control|45:: DL380e's config={'oob': {'hostname': '10.0.0.59', 'username': 'Administrator', 'password': 'xyz'}, 'os': {'password': None}, 'cpu': 'HP iLO 4', 'speed': 'HP iLO 4', 'drive': 'SMART', 'gpu': 'None', 'delay': 30, 'algo': {'cpu': {'type': 'curve', 'curve': {'temp': {'Min': 30, 'Low': 40, 'Medium': 50, 'High': 60, 'Max': 70}, 'speed': {'Min': 5, 'Low': 20, 'Medium': 50, 'High': 70, 'Max': 100}}}, 'drive': {'type': 'curve', 'curve': {'temp': {'Min': 30, 'Low': 40, 'Medium': 50, 'High': 60, 'Max': 70}, 'speed': {'Min': 5, 'Low': 20, 'Medium': 50, 'High': 70, 'Max': 100}}}}}!
2024-03-28T06:33:19.298415635Z 2024-03-28 06:33:19,297-ERROR-hush.control-1::control|46:: cannot convert float NaN to integer
2024-03-28T06:33:19.298448097Z Traceback (most recent call last):
2024-03-28T06:33:19.298460709Z   File "/app/hush/control.py", line 40, in run
2024-03-28T06:33:19.298479721Z     await self._calc()
2024-03-28T06:33:19.298484486Z   File "/app/hush/control.py", line 57, in _calc
2024-03-28T06:33:19.298489421Z     meas_temp = await driver.get_temp()
2024-03-28T06:33:19.298494192Z                 ^^^^^^^^^^^^^^^^^^^^^^^
2024-03-28T06:33:19.298498909Z   File "/app/hush/hardware/smart.py", line 52, in get_temp
2024-03-28T06:33:19.298520257Z     raise e
2024-03-28T06:33:19.298524943Z   File "/app/hush/hardware/smart.py", line 47, in get_temp
2024-03-28T06:33:19.298529798Z     self._temp = int(np.mean(drive_temps))
2024-03-28T06:33:19.298534744Z                  ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-28T06:33:19.298539515Z ValueError: cannot convert float NaN to integer
```

My config file is the following:

```
root@d3f3a83d23fc:/app/data# cat config 
Host DL380e
    IdentityFile /app/data/id_rsa
    StrictHostKeychecking no
    IdentitiesOnly yes
    PasswordAuthentication no
    HostName 10.0.0.110
    User root

Host DL380e_oob
    IdentityFile /app/data/id_rsa
    StrictHostKeychecking no
    IdentitiesOnly yes
    PasswordAuthentication yes
    HostName 10.0.0.59
    User Administrator
    PubKeyAcceptedKeyTypes +ssh-rsa
    HostKeyAlgorithms +ssh-dss
    KexAlgorithms +diffie-hellman-group14-sha1
```

**Comment by danielcbit** [comment]
Hi @natankeddem 

I've commented in the Pull Request, but the latest release fixes the SMART for me! Thank you!

However, another thing I will test and will send a separate PR is that in my setup I have a NVMe drive as my main drive and a SDCARD as boot drive (I couldn't enable the NVMe as boot drive in BIOS). 

Of course the SDCARD does not provide any temp readings, and because the NVMe was not being properly detected anymore, this was being bubbled up as a Connection Error ( which lead to the entire SSH connection investigation ) but in fact it should be a warning that no temperature info was detected.

**Comment by natankeddem** [comment]
The SMART driver should gracefully skip over any drives even if they don't provide parsable temperature readings. For example I have 2 random USB drives installed that don't give any temperatures using `smartctl -x {drive_path} | grep -E "Temperature|temperature"`.
```
2024-04-02 19:14:06,242-INFO-hush.hardware.smart-424541::smart|32::  failed to get drive temperature /dev/sde:
2024-04-02 19:14:06,243-INFO-hush.hardware.smart-424541::smart|33:: result = Result(name='', command=' ssh -F /hush/data/config abc smartctl -x /dev/sde | grep -E "Temperature|temperature"', return_code=1, stdout_lines=[], stderr_lines=[], terminated=False, truncated=False, data=None, trace='', cached=False, status='success', timestamp=1712099646.2421458)
2024-04-02 19:14:06,586-INFO-hush.hardware.smart-424541::smart|32::  failed to get drive temperature /dev/sdf:
2024-04-02 19:14:06,587-INFO-hush.hardware.smart-424541::smart|33:: result = Result(name='', command=' ssh -F /hush/data/config abc smartctl -x /dev/sdf | grep -E "Temperature|temperature"', return_code=1, stdout_lines=[], stderr_lines=[], terminated=False, truncated=False, data=None, trace='', cached=False, status='success', timestamp=1712099646.5864496)
2024-04-02 19:14:06,589-INFO-hush.control-424541::control|79:: 10.143.24.76 Temperature=22 -> Fan Speed=20
```
Therefore it logs the failure to acquire the temperature from those drives but it doesn't cause any errors. I would be interested in the output from `smartctl -x {drive_path} | grep -E "Temperature|temperature"` for your SD card. Perhaps,  regex is failing to parse something correctly.

**Comment by natankeddem** [comment]
I finally got some time to run some of my own tests. I installed SD cards in the onboard ports on both a Dell R720 and HP Gen8 Microserver. In both cases running Proxmox 8.1.10. I received no errors in either case. In both cases the SD card failed to read a temperature as expected and was gracefully handled. Therefore, I will need more information to assist in helping you with your issue.
